# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:

    runs-on: aws

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


  deploy:

    runs-on: aws

    steps:
      - name: Get the tag
        uses: olegtarasov/get-tag@v2.1.4
        id: tagName

      - name: Use tag
        run: echo "Tag is ${{ steps.tagName.outputs.tag }}"
    

      - name: Run SSH command to remote VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            git clone https://github.com/rahul-08-11/ci-and-cd-aws.git
            cd ci-and-cd-aws/
            sudo docker build -t  ci-and-cd-aws/dev:${{ steps.tagName.outputs.tag }} .
            ## clean docker
            sudo docker container stop $(sudo docker container ls -q)
            sudo docker container rm $(sudo docker container ls -q)
            ## run new version of dev
            sudo docker run -d -p 8000:8000 ci-and-cd-aws/dev:${{ steps.tagName.outputs.tag }}
            sudo docker system prune -a --volumes -f

            
  
        
    
